version: "3.0"
services:
  api_server:
    build: .
    volumes:
      - .dockervenv:/src/.dockerenv
      - .:/src
    ports:
      - "8000:8000"
  db_server:
    image: mysql:8.0
    platform: linux/x86_64 
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes' 
      MYSQL_DATABASE: 'demo' 
      TZ: 'Asia/Tokyo' 
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password 
    ports:
      - 33306:3306  
volumes:
  mysql_data:
